### PR TITLE
restrict tenant name upto 63 characters DNS restrictions

### LINKED ISSUE #895: No metrics are available when the tenant name is too long
## Expected Behavior
If the tenant name is too long, minio-operator should not allow it and enforce a safe limit on its name. Otherwise, the prometheus statefulset cannot start its pod.

## Current Behavior
And here's why the pod cannot be created, assuming the name of the tenant is `minio-1234567-123456-12345-production`:

```
create Pod minio-1234567-123456-12345-production-prometheus-0 in StatefulSet minio-1234567-123456-12345-production-prometheus failed error: Pod "minio-1234567-123456-12345-production-prometheus-0" is invalid: [spec.volumes[1].name: Invalid value: "minio-1234567-123456-12345-production-prometheus-config-volmount": must be no more than 63 characters,
```

## Possible Solution
Do not allow tenant names longer than `63 - strlen("-prometheus-config-volmount")`

### PR DESCRIPTION
**Pull request by harshavardhana**
Bonus: auto lookup namespace if none-provided.

fixes #895

### CODE REVIEW

File: kubectl-minio/cmd/tenant-expand.go [hunk 1]
```diff
@@ -96,6 +96,11 @@ func (v *expandCmd) validate(args []string) error {
 	if args[0] == "" {
 		return errors.New("provide the name of the tenant, e.g. 'kubectl minio tenant expand tenant1'")
 	}
+	// Tenant name should have DNS token restrictions
+	if err := helpers.CheckValidTenantName(args[0]); err != nil {
```
Comment (kanagarajkm) [inline kubectl-minio/cmd/tenant-expand.go:100]: This might be a problem for existing tenants with an invalid name. 

For example, if the tenant `mt` was created using an older version of the plugin and they cannot expand using the newer plugin.

Comment (harshavardhana) [reply kubectl-minio/cmd/tenant-expand.go:100]: There will no existing tenants in working state @kanagarajkm since DNS cannot be created for them

Comment (harshavardhana) [reply kubectl-minio/cmd/tenant-expand.go:100]: However lower limit can be fixed.

**Comment by harshavardhana** [comment]
PTAL @kanagarajkm @dvaldivia @Alevsk

**Review by Alevsk — APPROVED** [review]
LGTM

**Review by dvaldivia — APPROVED** [review]
