### PR TITLE
fix: incorrect error log `Waiting for MinIO to be ready: %!s(<nil>)`

### LINKED ISSUE #2308: Broken error log message: "Waiting for MinIO to be ready: %!s(<nil>)"
The - in principle correct - log message suffers from incorrect argument replacement. 

## Expected Behavior
The error log message is (correctly & expectedly) produced when the MinIO server processes are not (yet) ready.
Instead of "%!s(<nil>)" I expect to find some kind of description of the underlying error.

## Current Behavior
The log message hides the underlying error.

## Possible Solution
In `pkg/controller/main-controller.go`, L#1366 (v6.0.3, 45110b9d), change the message preparation so that a description of the underlying error/cause is printed in the message.

## Steps to Reproduce (for bugs)
1. Have a MinIO tenant up and running.
2. Make some changes to the tenant that induce temporary unavailability, like adding a new pool.

## Context
We are going to manage multiple clusters and strive for complete automation.
Therefore we need direct, succinct information in the log messages and can't effort to manually dig up the source-code, look what it does and what might have cause the error message in question.

## Regression
No

## Your Environment
* Version used (`minio-operator`): v6.0.3 
* Environment name and version (e.g. kubernetes v1.17.2): v1.30.0
* Server type and version: virtual
* Operating System and version (`uname -a`):  Linux minio-operator-74dc88668d-c56gh 6.6.43-talos #1 SMP Mon Aug  5 13:28:56 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: n/a

### PR DESCRIPTION
**Pull request by jiuker**
fix: incorrect error log
`Waiting for MinIO to be ready: %!s(<nil>)`
fix #2308

### CODE REVIEW

**Review by shtripat — APPROVED** [review]
lgtm

File: pkg/controller/main-controller.go [hunk 1]
```diff
@@ -1348,7 +1348,7 @@ func (c *Controller) syncHandler(key string) (Result, error) {
 	// Stay in this state until minio is ready
 	if tenant.Status.HealthStatus != miniov2.HealthStatusGreen {
 		c.updateTenantStatus(ctx, tenant, StatusWaitingMinIOIsHealthy, 0)
-		c.recorder.Event(tenant, corev1.EventTypeWarning, WaitingMinIOIsHealthyReason, fmt.Sprintf("Waiting for MinIO to be ready: %s", err))
+		c.recorder.Event(tenant, corev1.EventTypeWarning, WaitingMinIOIsHealthyReason, fmt.Sprintf("Waiting for MinIO(%s/%s) to be ready", tenant.Namespace, tenant.Name))
```
Comment (ramondeklein) [inline pkg/controller/main-controller.go:1351]: No need to log the namespace and name. It's logged in the tenant itself, so the namespace/name is already known.
```suggestion
		c.recorder.Event(tenant, corev1.EventTypeWarning, WaitingMinIOIsHealthyReason, "Waiting for MinIO to be ready")
```

**Review by ramondeklein — CHANGES_REQUESTED** [review]

**Review by shtripat — APPROVED** [review]

**Review by allanrogerr — APPROVED** [review]
LGTM

**Review by cesnietor — APPROVED** [review]
