### PR TITLE
Fix controller to update env vars

### LINKED ISSUE #394: Credentials in resources generated by kubectl plugin can not be customized.
From my understanding, the kubectl minio plugin has two modes:  in both modes, the resources necessary for the deployment of a Tenant are created from command line arguments and credentials are randomly created. Then, the resources are either directly applied to the cluster, or just outputted (using the -o yaml  switch).

According to the documentation, in the second case it should be possible to customize the resources and then to apply them manually to the Kubernetes cluster. However, it seems that changing the credentials (accesskey and secretkey in minio-creds-secret) from the randomly created ones to something custom is not possible.

My specific kubectl plugin command is
`kubectl minio tenant create --name minio --servers 1 --volumes 4 --capacity 1Gi --namespace my-namespace --storage-class my-storage-class`

When using the resources as created from the plugin, login to the Minio cluster using mc or the web UI on :9000 works.

## Expected Behavior
After changing the accesskey and secretkey to custom base64 encoded credentials in minio-creds-secret and removing and reapplying all resources (including the persistent volume claims), it should be possible to login to the Minio cluster using  these new credentials.

## Current Behavior
After changing the accesskey and secretkey, login is impossible. In the Web UI on :9000 and in mc, the returned error is "The access key ID you provided does not exist in our records". 
I verified in the Minio pods that the new accesskey and secretkey are correctly injected into the env vars MINO_ACCESS_KEY and MINIO_SECRET_KEY. After changing the credentials back to the original ones created by the kubectl plugin, login works again.

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
Described above.

## Context
I apply resources to my cluster using a GitOps approach with FluxCD. In this context, I want to choose custom credentials and want to encrypt them using the Sealed Secrets operator to avoid exposing them in my repository.
But what is most concerning for me that the bug/unexpected behaviour described suggests a dependency between the tenant and the generated credentials that can not be seen in the tenant resource. 

## Regression
I don't know

## Your Environment
* Version used (`minio-operator`): v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): kubectl v1.18.8, kubernetes v1.18.8+vmware.1
* Server type and version: v1.18.8+vmware.1
* Operating System and version (`uname -a`): Linux {hostname-redacted} 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: The resources can be directly created from the command above (by choosing a suitable storage class for your system)

### LINKED ISSUE #449: statefulSet not updated when updating env vars in tenant spec
While trying to update/add new env vars in the tenant spec, the tenant CRD is updated and the controller detects the update but the statefulset is not updated to reflect the change. 

## Steps to Reproduce (for bugs)
1. Have existing tenant
2. Update tenant CRD to add in some env var to spec: E.g
```
  env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
```
3. Operator log detects update  `main-controller.go:779] Successfully synced 'minio-testing/minio-testing`
3. Statefulset is not updated. 

## Your Environment
Operator
minio/k8s-operator:v3.0.29
Tenant
minio:RELEASE.2020-11-19T23-48-16Z

### PR DESCRIPTION
**Pull request by nitisht**
Controller now checks for changes in ENV vars and
updates the MinIO StatefulSet(s) accordingly.

Fixes #449
Fixes #394

### CODE REVIEW

File: pkg/controller/cluster/pools.go [hunk 1]
```diff
@@ -103,6 +103,9 @@ func poolSSMatchesSpec(tenant *miniov2.Tenant, pool *miniov2.Pool, ss *appsv1.St
 	if !reflect.DeepEqual(expectedMetadata.Annotations, ss.ObjectMeta.Annotations) {
 		poolMatchesSS = false
 	}
-
+	// Try to detect changes in Env Vars
+	if !miniov2.CompareEnvs(tenant.Spec.Env, ss.Spec.Template.Spec.Containers[0].Env) {
```
Comment (dvaldivia) [inline pkg/controller/cluster/pools.go:107]: I think this could return false very time, since not all the environment variables in `volumesPerServer: 1` match  `spec.Env` since we add extra environment variables, such as the webhook to operator and other, perhaps

Comment (nitisht) [reply pkg/controller/cluster/pools.go:107]: You're right, let me look at another approach.

Comment (nitisht) [reply pkg/controller/cluster/pools.go]: @dvaldivia this is fixed. Can you PTAL again.

File: pkg/apis/minio.min.io/v2/helper.go [hunk 2]
```diff
@@ -813,3 +813,34 @@ func MergeMaps(a, b map[string]string) map[string]string {
 	}
 	return a
 }
+
+// IsEnvUpdated looks for new env vars in the old env vars and returns true if
+// new env vars are not found
+func IsEnvUpdated(old, new []corev1.EnvVar) bool {
```
Comment (harshavardhana) [inline pkg/apis/minio.min.io/v2/helper.go:819]: its easier to simply build a map and compare them using reflect.DeepEqual()

Comment (nitisht) [reply pkg/apis/minio.min.io/v2/helper.go]: done, PTAL

**Review by harshavardhana — APPROVED** [review]

**Review by Alevsk — APPROVED** [review]
